import { readFile } from 'node:fs/promises'
import { join } from 'node:path'
import { NextResponse } from 'next/server'

/** Path to the dashboard spec generated by hivemind tools. */
const SPEC_PATH = join(process.cwd(), '..', '..', '.hivemind', 'activity', 'state', 'dashboard-spec.json')

/** Fallback spec returned when no dashboard-spec.json file exists yet. */
const FALLBACK_SPEC = {
  root: 'dashboard',
  elements: {
    dashboard: {
      type: 'Stack',
      props: { gap: 4, className: 'p-4' },
      children: ['header', 'status-card'],
      visible: true,
    },
    header: {
      type: 'Heading',
      props: { level: 2, children: 'HiveMind Dashboard' },
      visible: true,
    },
    'status-card': {
      type: 'Card',
      props: { className: 'p-4' },
      children: ['status-text'],
      visible: true,
    },
    'status-text': {
      type: 'Text',
      props: { children: 'No dashboard spec found. Run hivemind tools to generate dashboard data.' },
      visible: true,
    },
  },
}

/** CORS headers for local development. */
const CORS_HEADERS = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Methods': 'GET, OPTIONS',
  'Access-Control-Allow-Headers': 'Content-Type',
}

/**
 * GET /api/dashboard
 *
 * Reads the dashboard spec from `.hivemind/activity/state/dashboard-spec.json`.
 * Returns the fallback spec when the file does not exist.
 */
export async function GET() {
  try {
    const raw = await readFile(SPEC_PATH, 'utf-8')
    const spec = JSON.parse(raw)
    return NextResponse.json(spec, { headers: CORS_HEADERS })
  } catch {
    return NextResponse.json(FALLBACK_SPEC, { headers: CORS_HEADERS })
  }
}

/** Handle CORS preflight requests. */
export async function OPTIONS() {
  return new NextResponse(null, { status: 204, headers: CORS_HEADERS })
}
