import type { SlashCommandBundle } from './command-types.js'
import { getRuntimePressureContract } from '../../shared/pressure-contract.js'

export const slashCommandBundles: SlashCommandBundle[] = [
  {
    id: 'hm-init',
    title: 'Initialize control plane',
    controlPlanePrimitiveId: 'hm-init',
    agent: 'hivefiver',
    lineages: ['hivefiver', 'hiveminder'],
    purposeClasses: ['planning', 'implementation'],
    commandFile: 'hm-init.md',
    workflowChain: ['bootstrap.profile', 'bootstrap.governance', 'bootstrap.readiness'],
    toolGrantIds: ['prompt-transformation', 'context-injection'],
    structuredOutput: 'bootstrap-report',
    continuationMode: 'resume',
    autoRouteAllowed: true,
    workflowPhase: 'recovery-checkpoint',
    hostEvent: 'slash-command.requested',
    stateAuthority: 'workflow',
    pressureContract: getRuntimePressureContract('fresh-bootstrap'),
  },
  {
    id: 'hm-doctor',
    title: 'Repair broken control plane',
    controlPlanePrimitiveId: 'hm-doctor',
    agent: 'hivefiver',
    lineages: ['hivefiver', 'hiveminder'],
    purposeClasses: ['course-correction', 'gatekeeping'],
    commandFile: 'hm-doctor.md',
    workflowChain: ['doctor.audit', 'doctor.repair', 'doctor.confirm'],
    toolGrantIds: ['runtime-loader', 'workflow-integration'],
    structuredOutput: 'doctor-report',
    continuationMode: 'handoff',
    autoRouteAllowed: true,
    workflowPhase: 'recovery-checkpoint',
    hostEvent: 'slash-command.requested',
    stateAuthority: 'recovery',
    pressureContract: getRuntimePressureContract('control-plane-repair'),
  },
  {
    id: 'hm-harness',
    title: 'Validate workflow readiness',
    controlPlanePrimitiveId: 'hm-harness',
    agent: 'hivefiver',
    lineages: ['hivefiver', 'hiveminder'],
    purposeClasses: ['planning', 'implementation', 'gatekeeping', 'tdd'],
    commandFile: 'hm-harness.md',
    workflowChain: ['harness.readiness', 'harness.integration', 'harness.validation'],
    toolGrantIds: ['runtime-loader', 'workflow-integration'],
    structuredOutput: 'harness-report',
    continuationMode: 'iterative',
    autoRouteAllowed: true,
    workflowPhase: 'workflow-readiness',
    hostEvent: 'slash-command.requested',
    stateAuthority: 'workflow',
    pressureContract: getRuntimePressureContract('workflow-readiness'),
  },
  {
    id: 'hm-settings',
    title: 'Reconfigure control plane settings',
    controlPlanePrimitiveId: 'hm-settings',
    agent: 'hivefiver',
    lineages: ['hivefiver', 'hiveminder'],
    purposeClasses: ['planning'],
    commandFile: 'hm-settings.md',
    workflowChain: ['settings.profile', 'settings.governance', 'settings.guardrails'],
    toolGrantIds: ['prompt-transformation'],
    structuredOutput: 'settings-report',
    continuationMode: 'resume',
    autoRouteAllowed: false,
    workflowPhase: 'governance-projection',
    hostEvent: 'slash-command.requested',
    stateAuthority: 'plugin-control-plane',
    pressureContract: getRuntimePressureContract('steady-state'),
  },
  {
    id: 'hm-research',
    title: 'Run research and synthesis workflow',
    agent: 'hiverd',
    lineages: ['hivefiver', 'hiveminder'],
    purposeClasses: ['research'],
    commandFile: 'hm-research.md',
    workflowChain: ['research.intake', 'research.synthesis', 'research.handoff'],
    toolGrantIds: ['prompt-transformation', 'workflow-integration'],
    structuredOutput: 'research-report',
    continuationMode: 'handoff',
    autoRouteAllowed: true,
    workflowPhase: 'command-transition',
    hostEvent: 'slash-command.requested',
    stateAuthority: 'delegation',
    pressureContract: getRuntimePressureContract('delegated-handoff'),
  },
  {
    id: 'hm-plan',
    title: 'Build structured implementation plan',
    agent: 'hiveplanner',
    lineages: ['hivefiver', 'hiveminder'],
    purposeClasses: ['planning'],
    commandFile: 'hm-plan.md',
    workflowChain: ['planning.distill', 'planning.route', 'planning.gate'],
    toolGrantIds: ['prompt-transformation', 'workflow-integration'],
    structuredOutput: 'plan-report',
    continuationMode: 'resume',
    autoRouteAllowed: true,
    workflowPhase: 'command-transition',
    hostEvent: 'slash-command.requested',
    stateAuthority: 'workflow',
    pressureContract: getRuntimePressureContract('workflow-readiness'),
  },
  {
    id: 'hm-implement',
    title: 'Execute implementation workflow',
    agent: 'hivemaker',
    lineages: ['hivefiver', 'hiveminder'],
    purposeClasses: ['implementation'],
    commandFile: 'hm-implement.md',
    workflowChain: ['implementation.context', 'implementation.execute', 'implementation.verify'],
    toolGrantIds: ['context-injection', 'workflow-integration'],
    structuredOutput: 'implementation-report',
    continuationMode: 'iterative',
    autoRouteAllowed: true,
    workflowPhase: 'command-transition',
    hostEvent: 'slash-command.requested',
    stateAuthority: 'workflow',
    pressureContract: getRuntimePressureContract('task-mutation'),
  },
  {
    id: 'hm-verify',
    title: 'Run verification and review workflow',
    agent: 'hiveq',
    lineages: ['hivefiver', 'hiveminder'],
    purposeClasses: ['gatekeeping'],
    commandFile: 'hm-verify.md',
    workflowChain: ['verification.review', 'verification.trace', 'verification.verdict'],
    toolGrantIds: ['runtime-loader', 'workflow-integration'],
    structuredOutput: 'verification-report',
    continuationMode: 'handoff',
    autoRouteAllowed: true,
    workflowPhase: 'command-transition',
    hostEvent: 'slash-command.requested',
    stateAuthority: 'workflow',
    pressureContract: getRuntimePressureContract('handoff-validation'),
  },
  {
    id: 'hm-tdd',
    title: 'Enforce test-driven development flow',
    agent: 'verifier',
    lineages: ['hivefiver', 'hiveminder'],
    purposeClasses: ['tdd'],
    commandFile: 'hm-tdd.md',
    workflowChain: ['tdd.red', 'tdd.green', 'tdd.refactor'],
    toolGrantIds: ['runtime-loader', 'workflow-integration'],
    structuredOutput: 'tdd-report',
    continuationMode: 'iterative',
    autoRouteAllowed: true,
    workflowPhase: 'command-transition',
    hostEvent: 'slash-command.requested',
    stateAuthority: 'workflow',
    pressureContract: getRuntimePressureContract('task-mutation'),
  },
  {
    id: 'hm-course-correct',
    title: 'Recover or realign an active workflow',
    agent: 'hivefiver',
    lineages: ['hivefiver', 'hiveminder'],
    purposeClasses: ['course-correction'],
    commandFile: 'hm-course-correct.md',
    workflowChain: ['recovery.diagnose', 'recovery.realign', 'recovery.resume'],
    toolGrantIds: ['runtime-loader', 'workflow-integration'],
    structuredOutput: 'recovery-report',
    continuationMode: 'handoff',
    autoRouteAllowed: true,
    workflowPhase: 'recovery-checkpoint',
    hostEvent: 'slash-command.requested',
    stateAuthority: 'recovery',
    pressureContract: getRuntimePressureContract('control-plane-repair'),
  },
]
