/**
 * HiveMind Governance Plugin — Compaction Hook (FULLY WIRED)
 *
 * Implements BLOCK → retrieve → purify → validate → inject → unblock flow.
 *
 * Deterministic script triggers on compaction:
 * 1. gx-handoff-purify.sh    → builds purified handoff archive
 * 2. gx-context-retrieve.sh  → synthesizes recovery context
 * 3. gx-semantic-validate.sh → validates chain integrity (stub until R4)
 * 4. gx-schema-sync.sh       → validates all state files before compaction
 *
 * Cross-platform: macOS + Linux + Windows (Git Bash / WSL)
 */

import { readFileSync, existsSync } from "node:fs"
import { join } from "node:path"
import { formatEnforcementSummary, saveEnforcementState, runGxScript } from "../utils"
import type { EnforcementState, CompactionRecovery, CompactionHiveOpsContext, SotIndex, MemsGraph, BrainState } from "../types"

/**
 * Build the experimental.session.compacting hook.
 *
 * Flow: BLOCK → purify → retrieve → validate → synthesize → inject → unblock
 */
export function buildCompactionHook(state: {
  current: EnforcementState
  save: (s: EnforcementState) => void
  worktree: string
}) {
  return async (_input: any, output: any) => {
    // ── Phase 1: BLOCK ──
    state.current = {
      ...state.current,
      lastCheckpoint: Date.now(),
    }
    state.save(state.current)

    try {
      // ── Phase 2: PURIFY — build handoff archive before compaction ──
      runGxScript(state.worktree, "gx-handoff-purify.sh")

      // ── Phase 3: VALIDATE — check all state file schemas ──
      runGxScript(state.worktree, "gx-schema-sync.sh", ["check-all"])

      // ── Phase 4: VALIDATE CHAIN — semantic chain integrity (stub until R4) ──
      runGxScript(state.worktree, "gx-semantic-validate.sh", ["compaction"])

      // ── Phase 5: RETRIEVE — synthesize recovery context ──
      runGxScript(state.worktree, "gx-context-retrieve.sh")

      // ── Phase 6: SYNTHESIZE + INJECT ──
      const recovery = loadRecoveryFile(state.worktree)
      const hiveopsCtx = loadHiveOpsContext(state.worktree, state.current)
      const contextBlock = synthesizeContext(state.current, recovery, hiveopsCtx)

      if (output.context && Array.isArray(output.context)) {
        output.context.push(contextBlock)
      }
    } catch (err) {
      // On failure, fall back to basic governance injection
      const fallbackContext = buildFallbackContext(state.current)
      if (output.context && Array.isArray(output.context)) {
        output.context.push(fallbackContext)
      }
    } finally {
      // ── Phase 7: UNBLOCK ──
      state.current = {
        ...state.current,
        lastCheckpoint: Date.now(),
      }
      state.save(state.current)
    }
  }
}

/**
 * Load the context-recovery.json file generated by gx-context-retrieve.sh
 */
function loadRecoveryFile(worktree: string): CompactionRecovery | null {
  const recoveryPath = join(worktree, ".hivemind/state/context-recovery.json")
  if (!existsSync(recoveryPath)) return null

  try {
    const raw = readFileSync(recoveryPath, "utf-8")
    const parsed = JSON.parse(raw)

    return {
      trajectory_summary: parsed.trajectory_summary ?? "No trajectory data",
      active_todos: Array.isArray(parsed.active_todos)
        ? parsed.active_todos.map((t: any) => typeof t === "string" ? t : (t.content ?? String(t)))
        : [],
      key_decisions: Array.isArray(parsed.key_decisions)
        ? parsed.key_decisions.map((d: any) => typeof d === "string" ? d : (d.content ?? String(d)))
        : [],
      workflow_positions: Array.isArray(parsed.workflow_positions)
        ? parsed.workflow_positions.map((w: any) => ({
            workflow_id: w.workflow_id ?? "unknown",
            current_step: w.current_step ?? 0,
            step_name: w.step_name ?? "unknown",
          }))
        : [],
      health_summary: parsed.health_summary
        ? {
            score: parsed.health_summary.score ?? 0,
            status: parsed.health_summary.status ?? "unknown",
            degraded_signals: Array.isArray(parsed.health_summary.degraded_signals)
              ? parsed.health_summary.degraded_signals
              : [],
          }
        : { score: 0, status: "unknown", degraded_signals: [] },
      recommended_next: parsed.recommended_next ?? "No recommendation",
      recovered_at: Date.now(),
    }
  } catch {
    return null
  }
}

/**
 * Load hiveops state files for richer compaction recovery context.
 * Each file is read independently — failure of one does not block others.
 */
function loadHiveOpsContext(worktree: string, enforcement: EnforcementState): CompactionHiveOpsContext {
  const ctx: CompactionHiveOpsContext = {
    sotSummary: { totalArtifacts: 0, freshCount: 0, staleCount: 0, topDomains: [] },
    recentDecisions: [],
    brainMetrics: { turnCount: 0, driftScore: 0, healthScore: 0 },
    delegationChain: enforcement.delegationChain,
    activeGates: enforcement.gatesPassed,
  }

  // SOT index
  try {
    const sotPath = join(worktree, ".hivemind/state/sot-index.json")
    if (existsSync(sotPath)) {
      const sotIndex = JSON.parse(readFileSync(sotPath, "utf-8")) as SotIndex
      const artifacts = sotIndex.artifacts ?? []
      const fresh = artifacts.filter((a) => !a.stale)
      const stale = artifacts.filter((a) => a.stale)
      const domainCounts = new Map<string, number>()
      for (const a of artifacts) {
        domainCounts.set(a.domain, (domainCounts.get(a.domain) ?? 0) + 1)
      }
      const topDomains = [...domainCounts.entries()]
        .sort((a, b) => b[1] - a[1])
        .slice(0, 5)
        .map(([d]) => d)

      ctx.sotSummary = {
        totalArtifacts: artifacts.length,
        freshCount: fresh.length,
        staleCount: stale.length,
        topDomains,
      }
    }
  } catch {
    // Non-critical — continue with defaults
  }

  // Mems graph — extract recent decisions
  try {
    const memsPath = join(worktree, ".hivemind/graph/mems.json")
    if (existsSync(memsPath)) {
      const memsGraph = JSON.parse(readFileSync(memsPath, "utf-8")) as MemsGraph
      const decisions = (memsGraph.mems ?? [])
        .filter((m) => m.shelf === "decisions" || m.shelf === "insights")
        .sort((a, b) => new Date(b.created_at).getTime() - new Date(a.created_at).getTime())
        .slice(0, 10)
        .map((m) => ({ shelf: m.shelf, content: m.content, created_at: m.created_at }))
      ctx.recentDecisions = decisions
    }
  } catch {
    // Non-critical — continue with defaults
  }

  // Brain state — extract metrics
  try {
    const brainPath = join(worktree, ".hivemind/state/brain.json")
    if (existsSync(brainPath)) {
      const brain = JSON.parse(readFileSync(brainPath, "utf-8")) as BrainState
      ctx.brainMetrics = {
        turnCount: brain.metrics?.turn_count ?? 0,
        driftScore: brain.metrics?.drift_score ?? 0,
        healthScore: brain.metrics?.auto_health_score ?? 0,
      }
    }
  } catch {
    // Non-critical — continue with defaults
  }

  return ctx
}

/**
 * Synthesize recovery data + governance state as context string for injection
 */
function synthesizeContext(
  enforcement: EnforcementState,
  recovery: CompactionRecovery | null,
  hiveops?: CompactionHiveOpsContext
): string {
  const sections: string[] = []

  sections.push(formatEnforcementSummary(enforcement))

  sections.push("")
  sections.push("## Scope Boundaries (MUST PRESERVE)")
  sections.push(`- Agent: ${enforcement.agent}`)
  sections.push(`- Delegation chain depth: ${enforcement.delegationChain.length}`)
  sections.push(`- Scope violations so far: ${enforcement.scopeViolations.length}`)

  sections.push("")
  sections.push("## CRITICAL RULES (survive compaction)")
  sections.push("- DO NOT edit files outside your scope boundaries")
  sections.push("- DO NOT delegate to agents not in your delegation topology")
  sections.push("- ALWAYS run quality gates before claiming completion")
  sections.push("- ALWAYS update TODO list after completing work items")

  // HiveOps SOT summary (survives compaction for continuity)
  if (hiveops && hiveops.sotSummary.totalArtifacts > 0) {
    sections.push("")
    sections.push("## SOT Registry Summary (survive compaction)")
    sections.push(`- Total artifacts: ${hiveops.sotSummary.totalArtifacts} (${hiveops.sotSummary.freshCount} fresh, ${hiveops.sotSummary.staleCount} stale)`)
    if (hiveops.sotSummary.topDomains.length > 0) {
      sections.push(`- Top domains: ${hiveops.sotSummary.topDomains.join(", ")}`)
    }
  }

  // HiveOps recent decisions from mems graph
  if (hiveops && hiveops.recentDecisions.length > 0) {
    sections.push("")
    sections.push("## Recent Decisions (from mems graph)")
    for (const dec of hiveops.recentDecisions.slice(0, 5)) {
      sections.push(`- [${dec.shelf}] ${dec.content}`)
    }
  }

  // HiveOps brain metrics
  if (hiveops && (hiveops.brainMetrics.turnCount > 0 || hiveops.brainMetrics.driftScore > 0)) {
    sections.push("")
    sections.push("## Brain Metrics (survive compaction)")
    sections.push(`- Turn count: ${hiveops.brainMetrics.turnCount}`)
    sections.push(`- Drift score: ${hiveops.brainMetrics.driftScore}`)
    sections.push(`- Health score: ${hiveops.brainMetrics.healthScore}`)
  }

  if (recovery) {
    if (recovery.key_decisions.length > 0) {
      sections.push("")
      sections.push("## Key Decisions (from pre-compaction state)")
      for (const dec of recovery.key_decisions.slice(0, 10)) {
        sections.push(`- ${dec}`)
      }
    }

    if (recovery.active_todos.length > 0) {
      sections.push("")
      sections.push("## Active TODO Items (from pre-compaction state)")
      for (const todo of recovery.active_todos) {
        sections.push(`- ${todo}`)
      }
    }

    if (recovery.workflow_positions.length > 0) {
      sections.push("")
      sections.push("## Workflow Positions (from pre-compaction state)")
      for (const wf of recovery.workflow_positions) {
        sections.push(`- ${wf.workflow_id}: step ${wf.current_step} (${wf.step_name})`)
      }
    }

    sections.push("")
    sections.push("## Health Summary (from pre-compaction state)")
    sections.push(`- Composite score: ${recovery.health_summary.score}`)
    sections.push(`- Status: ${recovery.health_summary.status}`)
    if (recovery.health_summary.degraded_signals.length > 0) {
      sections.push(`- Degraded signals: ${recovery.health_summary.degraded_signals.join(", ")}`)
    }

    if (recovery.recommended_next !== "No recommendation") {
      sections.push("")
      sections.push("## Recommended Next Action")
      sections.push(`- ${recovery.recommended_next}`)
    }
  }

  return sections.join("\n")
}

/**
 * Fallback context when all retrieval fails
 */
function buildFallbackContext(enforcement: EnforcementState): string {
  return [
    formatEnforcementSummary(enforcement),
    "",
    "## Scope Boundaries (MUST PRESERVE)",
    `- Agent: ${enforcement.agent}`,
    `- Delegation chain depth: ${enforcement.delegationChain.length}`,
    `- Scope violations so far: ${enforcement.scopeViolations.length}`,
    "",
    "## CRITICAL RULES (survive compaction)",
    "- DO NOT edit files outside your scope boundaries",
    "- DO NOT delegate to agents not in your delegation topology",
    "- ALWAYS run quality gates before claiming completion",
    "- ALWAYS update TODO list after completing work items",
    "",
    "## WARNING: Context recovery failed",
    "- Pre-compaction state could not be retrieved",
    "- You may have lost decisions, TODO state, and workflow positions",
    "- Run gx-context-retrieve.sh manually to rebuild context",
  ].join("\n")
}
